export const psold_curves = [
  {"ID": 2016, "name": "2016"},
  {"ID": 2020, "name": "2020"}];

export const fls_curves = [
  {"ID": 1, "name": "Skandia - Low Combustibility"},
  {"ID": 2, "name": "Skandia - Normal Combustibility"},
  {"ID": 3, "name": "Skandia - High Combustibility"},
  {"ID": 4, "name": "Swiss Re - 50,000 to 100,000 Francs (Renters)"},
  {"ID": 5, "name": "Swiss Re - 100,000 to 250,000 Francs (Homeowners)"},
  {"ID": 6, "name": "Swiss Re - 250,000 to 500,000 Francs (Small Commercial)"},
  {"ID": 7, "name": "Swiss Re - over 500,000 Francs (Large Commercial)"},
  {"ID": 8, "name": "Munich - Property (U.K.)"},
  {"ID": 9, "name": "Munich - Property - Above Average"},
  {"ID": 10, "name": "Munich - Property - Average"},
  {"ID": 11, "name": "Munich - Property - Below Average #1"},
  {"ID": 12, "name": "Munich - Property - Below Average #2"},
  {"ID": 13, "name": "Hartford Commercial Fire - Retail"},
  {"ID": 14, "name": "Hartford Commercial Fire - Service"},
  {"ID": 15, "name": "Hartford Commercial Fire - Apartments"},
  {"ID": 16, "name": "Hartford Commercial Fire - Restaurants"},
  {"ID": 17, "name": "ISO Commercial Fire - Habitational"},
  {"ID": 18, "name": "ISO Commercial Fire - Mercantile/Restaurant"},
  {"ID": 19, "name": "ISO Commercial Fire - Manufacturing"},
  {"ID": 20, "name": "ISO Commercial Fire - Nonmanufacturing/Storage"},
  {"ID": 21, "name": "ISO Commercial Fire - Total"},
  {"ID": 22, "name": "ISO Commercial Fire & Wind - Habitational"},
  {"ID": 23, "name": "ISO Commercial Fire & Wind - Mercantile/Restaurant"},
  {"ID": 24, "name": "ISO Commercial Fire & Wind - Manufacturing"},
  {"ID": 25, "name": "ISO Commercial Fire & Wind - Nonmanufacturing/Storage"},
  {"ID": 26, "name": "ISO Commercial Fire & Wind - Total"},
  {"ID": 27, "name": "ISO Commercial Wind - Habitational"},
  {"ID": 28, "name": "ISO Commercial Wind - Mercantile/Restaurant"},
  {"ID": 29, "name": "ISO Commercial Wind - Manufacturing"},
  {"ID": 30, "name": "ISO Commercial Wind - Nonmanufacturing/Storage"},
  {"ID": 31, "name": "ISO Commercial Wind - Total"},
  {"ID": 32, "name": "Pro-rata, Commercial"},
  {"ID": 33, "name": "Hartford H.O. Fire - Frame Protected"},
  {"ID": 34, "name": "Hartford H.O. Fire - Frame Unprotected"},
  {"ID": 35, "name": "Hartford H.O. Fire - Brick Protected"},
  {"ID": 36, "name": "Hartford H.O. Fire - Brick Unprotected"},
  {"ID": 37, "name": "Hartford H.O. Fire - Total"},
  {"ID": 38, "name": "Hartford H.O. Wind - Frame"},
  {"ID": 39, "name": "Hartford H.O. Wind - Brick"},
  {"ID": 40, "name": "Hartford H.O. Wind - Total"},
  {"ID": 41, "name": "Pro-rata, Homeowners"},
  {"ID": 42, "name": "Marine - Blue Water Hull"},
  {"ID": 43, "name": "Marine - Non Blue Water Hull"},
  {"ID": 44, "name": "Marine - Cargo"},
  {"ID": 45, "name": "GC UK Curve"},
  {"ID": 46, "name": "IMMEUB(FR)"},
  {"ID": 47, "name": "INCPE0(FR)"},
  {"ID": 48, "name": "INCPE35(FR)"},
  {"ID": 49, "name": "INCPE65(FR)"},
  {"ID": 50, "name": "RAGRIC(FR)"},
  {"ID": 51, "name": "RSIMPLES(FR)"},
  {"ID": 52, "name": "Lloyd's A"},
  {"ID": 53, "name": "Lloyd's B"},
  {"ID": 54, "name": "Lloyd's N"},
  {"ID": 55, "name": "Lloyd's C"},
  {"ID": 56, "name": "Lloyd's D"},
  {"ID": 57, "name": "User Defined"}];

export const mb_curves = [
  {"ID": 1, "name": "Skandia - Low Combustibility"},
  {"ID": 2, "name": "Skandia - Normal Combustibility"},
  {"ID": 3, "name": "Skandia - High Combustibility"},
  {"ID": 4, "name": "Swiss Re - 50,000 to 100,000 Francs (Renters)"},
  {"ID": 5, "name": "Swiss Re - 100,000 to 250,000 Francs (Homeowners)"},
  {"ID": 6, "name": "Swiss Re - 250,000 to 500,000 Francs (Small Commercial)"},
  {"ID": 7, "name": "Swiss Re - over 500,000 Francs (Large Commercial)"},
  {"ID": 8, "name": "Munich - Property (U.K.)"},
  {"ID": 9, "name": "Munich - Property - Above Average"},
  {"ID": 10, "name": "Munich - Property - Average"},
  {"ID": 11, "name": "Munich - Property - Below Average #1"},
  {"ID": 12, "name": "Munich - Property - Below Average #2"},
  {"ID": 13, "name": "Hartford Commercial Fire - Retail"},
  {"ID": 14, "name": "Hartford Commercial Fire - Service"},
  {"ID": 15, "name": "Hartford Commercial Fire - Apartments"},
  {"ID": 16, "name": "Hartford Commercial Fire - Restaurants"},
  {"ID": 17, "name": "ISO Commercial Fire - Habitational"},
  {"ID": 18, "name": "ISO Commercial Fire - Mercantile/Restaurant"},
  {"ID": 19, "name": "ISO Commercial Fire - Manufacturing"},
  {"ID": 20, "name": "ISO Commercial Fire - Nonmanufacturing/Storage"},
  {"ID": 21, "name": "ISO Commercial Fire - Total"},
  {"ID": 22, "name": "ISO Commercial Fire & Wind - Habitational"},
  {"ID": 23, "name": "ISO Commercial Fire & Wind - Mercantile/Restaurant"},
  {"ID": 24, "name": "ISO Commercial Fire & Wind - Manufacturing"},
  {"ID": 25, "name": "ISO Commercial Fire & Wind - Nonmanufacturing/Storage"},
  {"ID": 26, "name": "ISO Commercial Fire & Wind - Total"},
  {"ID": 27, "name": "ISO Commercial Wind - Habitational"},
  {"ID": 28, "name": "ISO Commercial Wind - Mercantile/Restaurant"},
  {"ID": 29, "name": "ISO Commercial Wind - Manufacturing"},
  {"ID": 30, "name": "ISO Commercial Wind - Nonmanufacturing/Storage"},
  {"ID": 31, "name": "ISO Commercial Wind - Total"},
  {"ID": 32, "name": "Pro-rata, Commercial"},
  {"ID": 33, "name": "Hartford H.O. Fire - Frame Protected"},
  {"ID": 34, "name": "Hartford H.O. Fire - Frame Unprotected"},
  {"ID": 35, "name": "Hartford H.O. Fire - Brick Protected"},
  {"ID": 36, "name": "Hartford H.O. Fire - Brick Unprotected"},
  {"ID": 37, "name": "Hartford H.O. Fire - Total"},
  {"ID": 38, "name": "Hartford H.O. Wind - Frame"},
  {"ID": 39, "name": "Hartford H.O. Wind - Brick"},
  {"ID": 40, "name": "Hartford H.O. Wind - Total"},
  {"ID": 41, "name": "Pro-rata, Homeowners"},
  {"ID": 42, "name": "Marine - Blue Water Hull"},
  {"ID": 43, "name": "Marine - Non Blue Water Hull"},
  {"ID": 44, "name": "Marine - Cargo"},
  {"ID": 45, "name": "GC UK Curve"},
  {"ID": 46, "name": "IMMEUB(FR)"},
  {"ID": 47, "name": "INCPE0(FR)"},
  {"ID": 48, "name": "INCPE35(FR)"},
  {"ID": 49, "name": "INCPE65(FR)"},
  {"ID": 50, "name": "RAGRIC(FR)"},
  {"ID": 51, "name": "RSIMPLES(FR)"},
  {"ID": 52, "name": "Lloyd's A"},
  {"ID": 53, "name": "Lloyd's B"},
  {"ID": 54, "name": "Lloyd's N"},
  {"ID": 55, "name": "Lloyd's C"},
  {"ID": 56, "name": "Lloyd's D"},
  {"ID": 57, "name": "User Defined(c - Swiss Re def DO NOT USE)"},
  {"ID": 58, "name": "User Defined(b,g)"},
  {"ID": 59, "name": "GA Liabs"},
  {"ID": 60, "name": "GA Hull"},
  {"ID": 61, "name": "Personal Lines"},
  {"ID": 62, "name": "Commercial Lines (Small Scale)"},
  {"ID": 63, "name": "Commercial Lines (Medium Scale)"},
  {"ID": 64, "name": "Y6: Captive Business interruption"},
  {"ID": 65, "name": "Y6: Captive Property Damage/ Business Interruption"},
  {"ID": 66, "name": "Y6: Captive Property Damage"},
  {"ID": 67, "name": "Industry and Large Commercial"},
  {"ID": 68, "name": "Lloyd's (Y5): Industry"},
  {"ID": 69, "name": "Large-Scale Industry/Multinational Companies (c=6)"},
  {"ID": 70, "name": "Large-Scale Industry/Multinational Companies (c=7)"},
  {"ID": 71, "name": "Large-Scale Industry/Multinational Companies (c=8)"},
  {"ID": 72, "name": "XL Re Hull"},
  {"ID": 73, "name": "XL Re Cargo"},
  {"ID": 74, "name": "China Hull1"},
  {"ID": 75, "name": "China Hull2"},
  {"ID": 76, "name": "China Cargo1"},
  {"ID": 77, "name": "China Cargo2"},
  {"ID": 78, "name": "China Cargo3"},
  {"ID": 79, "name": "Peru Cargo 1"},
  {"ID": 80, "name": "Peru Cargo 2"},
  {"ID": 81, "name": "Peru Cargo 3"},
  {"ID": 82, "name": "Casualty GL"},
  {"ID": 83, "name": "Casualty A"},
  {"ID": 84, "name": "Casualty B"},
  {"ID": 85, "name": "Casualty EL Curve #1"},
  {"ID": 86, "name": "Casualty EL Curve #2"},
  {"ID": 87, "name": "Casualty EL Curve #3"},
  {"ID": 88, "name": "Casualty C"}];
